version: '3.3'
services: 
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        container_name: docker-mysql
        environment:
            MYSQL_ROOT_PASSWORD: stellardict
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:

